### ISSUE TITLE
error

### ISSUE THREAD

**Issue by KeeganRen** [tneumann/splocs#3]
ren@keegan  /home/ren/Code/Deformation/splocs/splocs-master   python sploc.py ./data/h5/volker_aligned.h5 ./data/h5/volker_splocs.h5
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2645: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
sploc.py:60: RuntimeWarning: divide by zero encountered in double_scalars
  pre_scale_factor = 1 / np.std(X)
sploc.py:61: RuntimeWarning: invalid value encountered in multiply
  X *= pre_scale_factor
Traceback (most recent call last):
  File "sploc.py", line 170, in <module>
    args.output_anim)
  File "sploc.py", line 72, in main
    U, s, Vt = svd(R[:,idx,:].reshape(R.shape[0], -1).T, full_matrices=False)
  File "/usr/lib/python2.7/dist-packages/scipy/linalg/decomp_svd.py", line 89, in svd
    a1 = asarray_chkfinite(a)
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py", line 668, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

**Comment by tneumann** [comment]
There seems to be a problem with the input data you give the algorithm. For example, this here

`sploc.py:60: RuntimeWarning: divide by zero encountered in double_scalars
pre_scale_factor = 1 / np.std(X)`

says that you have input data that has a standard deviation of zero. To be honest I cannot say for sure unless I see the data that you give to sploc.py. Are you able to send this data, either attach it here or send it to me via mail?
