### ISSUE TITLE
GeodesicDistanceComputation outputs nan

### ISSUE THREAD

**Issue by bing-jian** [tneumann/splocs#6]
First thanks for making the code public! 

I am trying to use the code in geodesic.py to compute the geodesic distances for a given triangular mesh, however I am getting nan outputs.  Any ideas?  Many thanks in advance!

Below are some debug information I printed out:

 In [361]: gg = geodesic.GeodesicDistanceComputation(vv, ff)

In [362]: gg(0)
('u0', array([1., 0., 0., ..., 0., 0., 0.]))
('u', array([3120.75912386, 1470.38703496, 1378.19606602, ...,    0.        ,
          0.        ,    0.        ]))
('grad_u', array([[-5.03985517e+05,  3.43585037e+05,  2.14059926e+05],
       [ 7.41695996e+03,  1.76621389e+04, -3.11673185e+04],
       [ 5.52125021e+00, -8.78023615e+00, -7.32132490e+00],
       ...,
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]]))
('X', array([[ 0.77964253, -0.53151033, -0.33114091],
       [-0.20273969, -0.48278764,  0.85194643],
       [-0.43489439,  0.69159616,  0.57668155],
       ...,
       [        nan,         nan,         nan],
       [        nan,         nan,         nan],
       [        nan,         nan,         nan]]))
('cot1', array([0.44103681, 1.68879891, 0.60181697, ..., 0.85222178, 0.85941778,
       0.98085892]))
('cot2', array([2.95458538, 0.07467702, 0.83182017, ..., 0.0895237 , 0.09506078,
       0.07537141]))
('cot1', array([-0.08925637,  0.49554718,  0.34834233, ...,  0.98084458,
        0.96209922,  0.87677019]))
('cot2', array([0.44103681, 1.68879891, 0.60181697, ..., 0.85222178, 0.85941778,
       0.98085892]))
('cot1', array([2.95458538, 0.07467702, 0.83182017, ..., 0.0895237 , 0.09506078,
       0.07537141]))
('cot2', array([-0.08925637,  0.49554718,  0.34834233, ...,  0.98084458,
        0.96209922,  0.87677019]))
('Phi', array([-0.73051449, -0.72611411, -0.72558426, ...,         nan,
               nan,         nan]))
Out[362]: array([nan, nan, nan, ..., nan, nan, nan])

**Comment by tneumann** [comment]
Your mesh must contain only one connected component, and it should not contain any unreference vertices or ill-formed triangles. The code I wrote here is not robust to such meshes, sorry about that. Alternatively, you can try the geodesic distance computation code in [libigl](https://github.com/libigl/libigl), they have both exact and heat geodesic distance computation implemented.

If you still experience the problem you could send me the mesh (e.g. in .obj format) so that I can take a look.

**Comment by bing-jian** [comment]
Thomas,  thanks for the quick response.  You are right.  It turns out that the mesh I tried has three connected components. FYI,  the mesh came from a face model and the two eye balls are isolated from the main face part.   Your geodesic computation code works fine on each sub-mesh.
